version: '3'

services:
  # https-portal:
  #   image: steveltn/https-portal:1
  #   restart: always
  #   ports:
  #     - 3443:443
  #   environment:
  #     DOMAINS: 'https-portal -> http://host.docker.internal:8000'
  #     STAGE: local
  
  reverse-proxy:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./static:/usr/share/nginx/html
  
  redis:
    image: redis
    ports:
      - 6379:6379
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
