openapi: "3.0.0"
info:
  title: Record API
  version: 1.0.0
servers:
  - url: http://localhost:3000/dev
tags:
  - name: records
paths:
  /records/{date}:
    get:
      operationId: get-daily-record-by-date
      tags:
        - records
      summary: get daily record by date
      parameters:
        - in: path
          name: date
          schema:
            type: string
          required: true
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                required:
                  - date
                  - records
                properties:
                  date:
                    type: string
                    format: date
                  records:
                    type: array
                    items:
                      $ref: '#/components/schemas/Record'       

components:
  schemas:
    Record:
      type: object
      required:
        - date
        - startedAt
        - endedAt
      properties:
        date:
          type: string
          format: date
        startedAt:
          type: string
          format: time
        endedAt:
          type: string
          format: time