openapi: "3.0.0"
info:
  title: Record API
  version: 1.0.0
servers:
  - url: http://localhost:3000/dev
tags:
  - name: auth
  - name: records
paths:
  /auth:
    post:
      operationId: login
      tags:
        - auth
      summary: login with password
      requestBody:
        content:
          application/json:
            schema:
              required:
                - password
              properties:
                password:
                  type: string
      responses:
        '200':
          description: login successfull
  
  /me/id:
    get:
      operationId: get-my-id
      tags:
        - auth
      summary: returns my id
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                required:
                  - id
                properties:
                  id:
                    type: string
                  
  /records/{date}:
    get:
      operationId: get-daily-record-by-date
      tags:
        - records
      summary: get daily record by date
      parameters:
        - in: path
          name: date
          schema:
            type: string
          required: true
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                required:
                  - date
                  - records
                properties:
                  date:
                    type: string
                    format: date
                  records:
                    type: array
                    items:
                      $ref: '#/components/schemas/Record'
  /records/today/{label}:
    post:
      operationId: insert-record
      tags:
        - records
      summary: insert record with current time
      parameters:
        - in: path
          name: label
          schema:
            type: string
          required: true
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                required:
                  - date
                  - records
                properties:
                  date:
                    type: string
                    format: date
                  records:
                    type: array
                    items:
                      $ref: '#/components/schemas/Record'       

components:
  schemas:
    Record:
      type: object
      required:
        - label
        - startedAt
      properties:
        label:
          type: string
        startedAt:
          type: string
          format: time
