service: serverless-example

useDotenv: true
plugins:
  - serverless-scriptable-plugin
  - serverless-dynamodb
  - serverless-offline

package:
  exclude:
    - "**"
  include:
    - "dist/**"

custom:
  scriptable:
    hooks:
      offline:start:init: rm -rf dist; npx ncc build src/main.ts -a -m
  serverless-dynamodb:
    stages:
      - dev
    start:
      migrate: true
      seed: true
      inMemory: true
    seed:
      domain:
        sources:
          - table: ${env:DAILY_RECORD_TABLE}
            sources: [./src/dynamo/dailyRecord.json]

provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: nodejs14.x
  timeout: 10
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/dev.DailyRecord"
  environment:
    # SECRET_SESSION_KEY: ${ssm:/${self:provider.stage}/lambda-session-key}
    # DAILY_RECORD_TABLE: ${ssm:/${self:provider.stage}/daily-record-table}

functions:
  main:
    handler: dist/index.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

resources:
  Resources:
    TestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DAILY_RECORD_TABLE}
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
