/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/records/{id}': {
    /** get record by id */
    get: operations['get-record-by-id'];
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** get record by id */
  'get-record-by-id': {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 200 response */
      200: {
        content: {
          'application/json': {
            id: string;
          };
        };
      };
    };
  };
}
