/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth': {
    /** login with password */
    post: operations['login'];
  };
  '/me/id': {
    /** returns my id */
    get: operations['get-my-id'];
  };
  '/records/{date}': {
    /** get daily record by date */
    get: operations['get-daily-record-by-date'];
  };
  '/records/today/{label}': {
    /** insert record with current time */
    post: operations['insert-record'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Record: {
      label: string;
      /** Format: time */
      startedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {
  /** login with password */
  login: {
    requestBody: {
      content: {
        'application/json': {
          password: string;
        };
      };
    };
    responses: {
      /** @description login successfull */
      200: {
        content: {
          'application/json': {
            /** @example ok */
            status: string;
          };
        };
      };
    };
  };
  /** returns my id */
  'get-my-id': {
    responses: {
      /** @description 200 response */
      200: {
        content: {
          'application/json': {
            id: string;
          };
        };
      };
    };
  };
  /** get daily record by date */
  'get-daily-record-by-date': {
    parameters: {
      path: {
        date: string;
      };
    };
    responses: {
      /** @description 200 response */
      200: {
        content: {
          'application/json': {
            /** Format: date */
            date: string;
            records: components['schemas']['Record'][];
          };
        };
      };
    };
  };
  /** insert record with current time */
  'insert-record': {
    parameters: {
      path: {
        label: string;
      };
    };
    responses: {
      /** @description 200 response */
      200: {
        content: {
          'application/json': {
            /** Format: date */
            date: string;
            records: components['schemas']['Record'][];
          };
        };
      };
    };
  };
}
